- 👋 Hi, I’m @witty4056
- 👀 I’m interested in data analytics ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on data projects...
- 📫 How to reach me sarrichard19@gmail.com ...

<!---
witty4056/witty4056 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
